# Generated by Django 4.1.1 on 2022-10-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=50, verbose_name='Прізвище')),
                ('subject', models.CharField(max_length=100, verbose_name='Предмет')),
                ('link', models.URLField(verbose_name='Посилання в зум')),
                ('up_or_down_week', models.CharField(choices=[('1', 'ВЕРХНІЙ'), ('2', 'НИЖНІЙ')], default='1', max_length=10, verbose_name='Верхній чи нижній тиждень')),
                ('day_number', models.CharField(choices=[('1', 'ПОНЕДІЛОК'), ('2', 'ВІВТОРОК '), ('3', 'СЕРЕДА'), ('4', 'ЧЕТВЕР'), ('5', "П'ЯТНИЦЯ"), ('6', 'ПОНЕДІЛОК'), ('7', 'ВІВТОРОК '), ('8', 'СЕРЕДА'), ('9', 'ЧЕТВЕР'), ('10', "П'ЯТНИЦЯ")], default='1', max_length=10, verbose_name='День')),
                ('number_of_lesson', models.CharField(choices=[('1', 'ПЕРША ПАРА'), ('2', 'ДРУГА ПАРА'), ('3', 'ТРЕТЯ ПАРА'), ('4', 'ЧЕТВЕРТА ПАРА')], default='1', max_length=10, verbose_name='Пара')),
                ('last_changes', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
