# Generated by Django 4.1.1 on 2022-10-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_todo', '0002_alter_schedule_day_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_or_down_week', models.CharField(choices=[('1', 'ВЕРХНІЙ'), ('2', 'НИЖНІЙ')], default='1', max_length=10, verbose_name='Верхній чи нижній тиждень')),
            ],
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day_number', 'number_of_lesson']},
        ),
    ]
