# Generated by Django 4.1.1 on 2022-10-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_todo', '0003_maindata_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання в зум'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Предмет'),
        ),
    ]
