# Generated by Django 4.1.1 on 2022-10-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_todo', '0006_todoinformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoInformation',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання1'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='link2',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання2'),
        ),
    ]
