# Generated by Django 4.1.1 on 2022-10-18 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_todo', '0007_delete_todoinformation_alter_schedule_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindata',
            name='changed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
