# Generated by Django 4.1.1 on 2022-10-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_todo', '0008_maindata_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinesePhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
