# Generated by Django 4.1.1 on 2022-10-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_todo', '0009_chinesephrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chinesephrase',
            name='phrase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
