# Generated by Django 4.1.1 on 2022-10-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_todo', '0011_alter_chinesephrase_phrase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['pk']},
        ),
    ]
